### ISSUE TITLE
请问你的pytorch_lightning是哪个版本

### ISSUE THREAD

**Issue by Liekkas22years** [xusenlinzy/lightningblocks#1]
报这个错误：ImportError: cannot import name '_module_available' from 'pytorch_lightning'

**Comment by xusenlinzy** [comment]
您好，这边pytorch_lightning的版本是1.7.6

**Comment by xusenlinzy** [comment]
现在已经修改imports过的内容，git拉取之后支持1.8.3版本的pytorch_lightning
